import type { Metadata } from 'next'
import './globals.css'
import NavLinks from '@/app/ui/NavLinks'
import Providers from '@/components/ui/provider'
import { ThemeProvider } from '@/components/theme-provider'
import { ModeToggle } from '@/components/mode-toggle'
import { HomeIcon } from 'lucide-react'
import Link from 'next/link'
import { Button } from '@/components/ui/button'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="min-h-screen">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Providers>
            <div className="relative flex min-h-screen">
              {/* Sidebar */}
              <aside className="sticky top-0 flex h-screen w-52 flex-col border-r bg-background">
                <div className="flex h-14 items-center justify-between border-b px-4">
                  <Button variant="ghost" asChild className="gap-2">
                    <Link href="/">
                      <HomeIcon className="h-5 w-5" />
                      <span className="font-semibold">Home</span>
                    </Link>
                  </Button>
                  <ModeToggle />
                </div>
                <NavLinks />
              </aside>

              {/* Main Content */}
              <div className="flex-1">
                <header className="sticky top-0 z-50 h-14 border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
                  <div className="flex h-14 items-center px-6">
                    <div className="flex flex-1 items-center justify-between">
                      <h2 className="text-sm font-semibold">Dashboard</h2>
                    </div>
                  </div>
                </header>
                <main className="flex-1 p-6">
                  {children}
                </main>
              </div>
            </div>
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  )
}
