import type { Metadata } from 'next'
import './globals.css'
import NavLinks from '@/app/ui/NavLinks'
import Providers from '@/components/ui/provider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
          <div className="flex min-h-screen">
            <aside className="fixed inset-y-0 z-50 flex h-full w-52 flex-col border-r bg-background">
              <div className="border-b px-6 py-4">
                <h2 className="text-lg font-semibold">My App</h2>
              </div>
              <NavLinks />
            </aside>
            <main className="flex-1 pl-52">
              {children}
            </main>
          </div>
        </Providers>
      </body>
    </html>
  )
}
