import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
import './globals.css'
import SideNav from './ui/SideNav'
import Providers from '@/components/ui/provider'

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex">
          <div className="w-full md:w-64 h-full fixed left-0">
            <SideNav />
          </div>
          <Providers>
            <div className="ml-64 flex-grow p-6 md:overflow-y-auto md:p-12">{children}</div>
          </Providers>
        </div>
      </body>
    </html>
  )
}
